output:
  sort-results: true
  sort-order:
    - file
    - linter

linters:
  enable-all: true
  disable:
    - gomnd
    - depguard
    - exhaustruct
    - nonamedreturns
    - testpackage
    - paralleltest
    - execinquery
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/artemk1337/fparams)
  varnamelen:
    min-name-length: 2
issues:
  exclude-dirs:
    - pkg/analyzer/testdata
